### PR TITLE
Export ArithK

### PR DESCRIPTION
**Pull request by LightAndLight**
I've been fooling around with this packing and found that it's been helpful to have access to ArithK.

### CODE REVIEW

**Comment by adituv** [comment]
Thanks for the PR!  All the changes look good, but I'm wondering: what use-case do you have for `ArithK` to be exposed?  I don't particularly want to expose it as is without making a few changes first because it is a bit of a messy and potentially misleading implementation detail.

**Comment by LightAndLight** [comment]
Here's the code I've written that uses it

https://github.com/LightAndLight/ranged/blob/master/src/Data/Ranged.hs#L25

**Comment by adituv** [comment]
I see, that does make sense!  If it's ok with you, I'll move it to an exposed internal module and document it further rather than just export it as is.

Also, would open type families be useful for you, so you could just add new cases to the existing operators?

Edit: it seems like open type families don't work with GHC < 8.2.  I need to look into this some more still.

**Comment by LightAndLight** [comment]
Awesome, thanks :)

**Comment by adituv** [comment]
Unfortunately I can't get extending open type families to work at present, so I'm just going to push through the smaller fix to expose the kind families for you and leave that as a future improvement in #3.

**Pull request closed without merging**
